window.TAITHAI_REAL_SONGS = [
  { id: 'th-001', title: 'ซ่อนกลิ่น', artist: 'Palmy', language: 'thai', genre: 'Pop', key: 'C', capo: 'ไม่ระบุ' },
  { id: 'th-002', title: 'คิดถึง', artist: 'Bodyslam', language: 'thai', genre: 'Rock', key: 'G', capo: 'ไม่ระบุ' },
  { id: 'th-003', title: 'ความเชื่อ', artist: 'Bodyslam', language: 'thai', genre: 'Rock', key: 'D', capo: 'ไม่ระบุ' },
  { id: 'th-004', title: 'แสงสุดท้าย', artist: 'Bodyslam', language: 'thai', genre: 'Rock', key: 'A', capo: 'ไม่ระบุ' },
  { id: 'th-005', title: 'ยาพิษ', artist: 'Bodyslam', language: 'thai', genre: 'Rock', key: 'Em', capo: 'ไม่ระบุ' },
  { id: 'th-006', title: 'อกหัก', artist: 'Bodyslam', language: 'thai', genre: 'Rock', key: 'G', capo: 'ไม่ระบุ' },
  { id: 'th-007', title: 'เรือเล็กควรออกจากฝั่ง', artist: 'Bodyslam', language: 'thai', genre: 'Rock', key: 'C', capo: 'ไม่ระบุ' },
  { id: 'th-008', title: 'Sticker', artist: 'Bodyslam', language: 'thai', genre: 'Rock', key: 'D', capo: 'ไม่ระบุ' },
  { id: 'th-009', title: 'ฝุ่น', artist: 'Big Ass', language: 'thai', genre: 'Rock', key: 'C', capo: 'ไม่ระบุ' },
  { id: 'th-010', title: 'เล่นของสูง', artist: 'Big Ass', language: 'thai', genre: 'Rock', key: 'D', capo: 'ไม่ระบุ' },
  { id: 'th-011', title: 'ก่อนตาย', artist: 'Big Ass', language: 'thai', genre: 'Rock', key: 'G', capo: 'ไม่ระบุ' },
  { id: 'th-012', title: 'ทางผ่าน', artist: 'Pure', language: 'thai', genre: 'Pop', key: 'C', capo: 'ไม่ระบุ' },
  { id: 'th-013', title: 'ผู้ถูกเลือกให้ผิดหวัง', artist: 'เรนิษรา', language: 'thai', genre: 'Pop', key: 'D', capo: 'ไม่ระบุ' },
  { id: 'th-014', title: 'โต๊ะริม', artist: 'นนท์ ธนนท์', language: 'thai', genre: 'Pop', key: 'G', capo: 'ไม่ระบุ' },
  { id: 'th-015', title: 'พิง', artist: 'นนท์ ธนนท์', language: 'thai', genre: 'Pop', key: 'C', capo: 'ไม่ระบุ' },
  { id: 'th-016', title: 'เจ็บจนพอ', artist: 'Wanyai', language: 'thai', genre: 'Pop', key: 'Am', capo: 'ไม่ระบุ' },
  { id: 'th-017', title: 'ลืมไปแล้วว่าลืมยังไง', artist: 'Jeff Satur', language: 'thai', genre: 'Pop', key: 'G', capo: 'ไม่ระบุ' },
  { id: 'th-018', title: 'แค่เธอ', artist: 'Jeff Satur', language: 'thai', genre: 'Pop', key: 'D', capo: 'ไม่ระบุ' },
  { id: 'th-019', title: 'ถ้าเราเจอกันอีก', artist: 'Tilly Birds', language: 'thai', genre: 'Pop', key: 'C', capo: 'ไม่ระบุ' },
  { id: 'th-020', title: 'คิดแต่ไม่ถึง', artist: 'Tilly Birds', language: 'thai', genre: 'Pop', key: 'G', capo: 'ไม่ระบุ' },
  { id: 'th-021', title: 'เพื่อนเล่น ไม่เล่นเพื่อน', artist: 'Tilly Birds', language: 'thai', genre: 'Pop', key: 'D', capo: 'ไม่ระบุ' },
  { id: 'th-022', title: 'ฤดูที่ฉันเหงา', artist: 'Flure', language: 'thai', genre: 'Pop', key: 'C', capo: 'ไม่ระบุ' },
  { id: 'th-023', title: 'เธอทั้งนั้น', artist: 'Groove Riders', language: 'thai', genre: 'Pop', key: 'G', capo: 'ไม่ระบุ' },
  { id: 'th-024', title: 'หยุด', artist: 'Groove Riders', language: 'thai', genre: 'Pop', key: 'D', capo: 'ไม่ระบุ' },
  { id: 'th-025', title: 'โปรดส่งใครมารักฉันที', artist: 'Instinct', language: 'thai', genre: 'Rock', key: 'C', capo: 'ไม่ระบุ' },
  { id: 'th-026', title: 'ขอ', artist: 'Lomosonic', language: 'thai', genre: 'Rock', key: 'G', capo: 'ไม่ระบุ' },
  { id: 'th-027', title: 'ความรู้สึกของวันนี้', artist: 'Lomosonic', language: 'thai', genre: 'Rock', key: 'D', capo: 'ไม่ระบุ' },
  { id: 'th-028', title: 'ทิ้งไว้กลางทาง', artist: 'Potato', language: 'thai', genre: 'Rock', key: 'C', capo: 'ไม่ระบุ' },
  { id: 'th-029', title: 'ขอบคุณที่รักกัน', artist: 'Potato', language: 'thai', genre: 'Rock', key: 'G', capo: 'ไม่ระบุ' },
  { id: 'th-030', title: 'แพ้ทาง', artist: 'Labanoon', language: 'thai', genre: 'Rock', key: 'D', capo: 'ไม่ระบุ' },
  { id: 'th-031', title: 'เชือกวิเศษ', artist: 'Labanoon', language: 'thai', genre: 'Rock', key: 'G', capo: 'ไม่ระบุ' },
  { id: 'th-032', title: 'ใจกลางเมือง', artist: 'Labanoon', language: 'thai', genre: 'Rock', key: 'C', capo: 'ไม่ระบุ' },
  { id: 'th-033', title: 'กอด', artist: 'Clash', language: 'thai', genre: 'Rock', key: 'D', capo: 'ไม่ระบุ' },
  { id: 'th-034', title: 'เธอจะอยู่กับฉันตลอดไป', artist: 'Clash', language: 'thai', genre: 'Rock', key: 'G', capo: 'ไม่ระบุ' },
  { id: 'th-035', title: 'ใจนักเลง', artist: 'Pong Hin Lek Fai', language: 'thai', genre: 'Rock', key: 'A', capo: 'ไม่ระบุ' },
  { id: 'th-036', title: 'รักคงยังไม่พอ', artist: 'เสือ ธนพล', language: 'thai', genre: 'Rock', key: 'C', capo: 'ไม่ระบุ' },
  { id: 'th-037', title: 'เจ้าตาก', artist: 'คาราบาว', language: 'thai', genre: 'Rock', key: 'Am', capo: 'ไม่ระบุ' },
  { id: 'th-038', title: 'ทะเลใจ', artist: 'คาราบาว', language: 'thai', genre: 'Folk', key: 'C', capo: 'ไม่ระบุ' },
  { id: 'th-039', title: 'ลมเปลี่ยนทิศ', artist: 'Big Ass', language: 'thai', genre: 'Rock', key: 'G', capo: 'ไม่ระบุ' },
  { id: 'th-040', title: 'คนไม่จำเป็น', artist: 'Getsunova', language: 'thai', genre: 'Pop', key: 'D', capo: 'ไม่ระบุ' },
  { id: 'th-041', title: 'ไกลแค่ไหนคือใกล้', artist: 'Getsunova', language: 'thai', genre: 'Pop', key: 'C', capo: 'ไม่ระบุ' },
  { id: 'th-042', title: 'อยู่ต่อเลยได้ไหม', artist: 'สิงโต นำโชค', language: 'thai', genre: 'Pop', key: 'G', capo: 'ไม่ระบุ' },
  { id: 'th-043', title: 'รักแรกพบ', artist: 'Tattoo Colour', language: 'thai', genre: 'Pop', key: 'D', capo: 'ไม่ระบุ' },
  { id: 'th-044', title: 'โกหก', artist: 'Tattoo Colour', language: 'thai', genre: 'Pop', key: 'C', capo: 'ไม่ระบุ' },
  { id: 'th-045', title: 'ฟ้า', artist: 'Tattoo Colour', language: 'thai', genre: 'Pop', key: 'G', capo: 'ไม่ระบุ' },
  { id: 'th-046', title: 'มันคงเป็นความรัก', artist: 'Stamp', language: 'thai', genre: 'Pop', key: 'C', capo: 'ไม่ระบุ' },
  { id: 'th-047', title: 'สบู่', artist: 'Stamp', language: 'thai', genre: 'Pop', key: 'D', capo: 'ไม่ระบุ' },
  { id: 'th-048', title: 'ร่มสีเทา', artist: 'วัชราวลี', language: 'thai', genre: 'Folk', key: 'G', capo: 'ไม่ระบุ' },
  { id: 'th-049', title: 'ลูกอม', artist: 'วัชราวลี', language: 'thai', genre: 'Folk', key: 'C', capo: 'ไม่ระบุ' },
  { id: 'th-050', title: 'ลาลาลอย', artist: 'The Toys', language: 'thai', genre: 'Pop', key: 'Am', capo: 'ไม่ระบุ' },
  { id: 'th-051', title: 'หน้าหนาวที่แล้ว', artist: 'The Toys', language: 'thai', genre: 'Pop', key: 'G', capo: 'ไม่ระบุ' },
  { id: 'th-052', title: 'ก่อนฤดูฝน', artist: 'The Toys', language: 'thai', genre: 'Pop', key: 'D', capo: 'ไม่ระบุ' },
  { id: 'th-053', title: 'คุกกี้เสี่ยงทาย', artist: 'BNK48', language: 'thai', genre: 'Pop', key: 'C', capo: 'ไม่ระบุ' },
  { id: 'th-054', title: 'วาฬเกยตื้น', artist: 'Gungun', language: 'thai', genre: 'Pop', key: 'G', capo: 'ไม่ระบุ' },
  { id: 'th-055', title: 'แอบดี', artist: 'Stamp', language: 'thai', genre: 'Pop', key: 'D', capo: 'ไม่ระบุ' },
  { id: 'th-056', title: 'ฝนตกไหม', artist: 'Three Man Down', language: 'thai', genre: 'Pop', key: 'C', capo: 'ไม่ระบุ' },
  { id: 'th-057', title: 'ถ้าเธอรักฉันจริง', artist: 'Three Man Down', language: 'thai', genre: 'Pop', key: 'G', capo: 'ไม่ระบุ' },
  { id: 'th-058', title: 'ฝันถึงแฟนเก่า', artist: 'Three Man Down', language: 'thai', genre: 'Pop', key: 'D', capo: 'ไม่ระบุ' },
  { id: 'th-059', title: 'แค่คุณ', artist: 'Musketeers', language: 'thai', genre: 'Pop', key: 'C', capo: 'ไม่ระบุ' },
  { id: 'th-060', title: 'ของขวัญ', artist: 'Musketeers', language: 'thai', genre: 'Pop', key: 'G', capo: 'ไม่ระบุ' },
  { id: 'th-061', title: 'เหนื่อยไหมหัวใจ', artist: 'Retrospect', language: 'thai', genre: 'Rock', key: 'D', capo: 'ไม่ระบุ' },
  { id: 'th-062', title: 'ปล่อยฉัน', artist: 'Retrospect', language: 'thai', genre: 'Rock', key: 'Am', capo: 'ไม่ระบุ' },
  { id: 'th-063', title: 'คุกเข่า', artist: 'Cocktail', language: 'thai', genre: 'Rock', key: 'C', capo: 'ไม่ระบุ' },
  { id: 'th-064', title: 'เธอ', artist: 'Cocktail', language: 'thai', genre: 'Rock', key: 'G', capo: 'ไม่ระบุ' },
  { id: 'th-065', title: 'คู่ชีวิต', artist: 'Cocktail', language: 'thai', genre: 'Rock', key: 'D', capo: 'ไม่ระบุ' },
  { id: 'th-066', title: 'ดึงดัน', artist: 'Cocktail x ตั๊ก ศิริพร', language: 'thai', genre: 'Pop', key: 'C', capo: 'ไม่ระบุ' },
  { id: 'th-067', title: 'ภาพจำ', artist: 'ป๊อบ ปองกูล', language: 'thai', genre: 'Pop', key: 'G', capo: 'ไม่ระบุ' },
  { id: 'th-068', title: 'ปล่อย', artist: 'ป๊อบ ปองกูล', language: 'thai', genre: 'Pop', key: 'D', capo: 'ไม่ระบุ' },
  { id: 'th-069', title: 'ฉันยังอยู่', artist: 'Atom ชนกันต์', language: 'thai', genre: 'Pop', key: 'C', capo: 'ไม่ระบุ' },
  { id: 'th-070', title: 'Please', artist: 'Atom ชนกันต์', language: 'thai', genre: 'Pop', key: 'G', capo: 'ไม่ระบุ' },
  { id: 'en-001', title: 'Wonderwall', artist: 'Oasis', language: 'international', genre: 'Rock', key: 'Em', capo: 'ไม่ระบุ' },
  { id: 'en-002', title: 'Don\'t Look Back in Anger', artist: 'Oasis', language: 'international', genre: 'Rock', key: 'C', capo: 'ไม่ระบุ' },
  { id: 'en-003', title: 'Yesterday', artist: 'The Beatles', language: 'international', genre: 'Pop', key: 'F', capo: 'ไม่ระบุ' },
  { id: 'en-004', title: 'Let It Be', artist: 'The Beatles', language: 'international', genre: 'Pop', key: 'C', capo: 'ไม่ระบุ' },
  { id: 'en-005', title: 'Hey Jude', artist: 'The Beatles', language: 'international', genre: 'Pop', key: 'F', capo: 'ไม่ระบุ' },
  { id: 'en-006', title: 'Hotel California', artist: 'Eagles', language: 'international', genre: 'Rock', key: 'Bm', capo: 'ไม่ระบุ' },
  { id: 'en-007', title: 'Take It Easy', artist: 'Eagles', language: 'international', genre: 'Rock', key: 'G', capo: 'ไม่ระบุ' },
  { id: 'en-008', title: 'Perfect', artist: 'Ed Sheeran', language: 'international', genre: 'Pop', key: 'G', capo: 'ไม่ระบุ' },
  { id: 'en-009', title: 'Thinking Out Loud', artist: 'Ed Sheeran', language: 'international', genre: 'Pop', key: 'D', capo: 'ไม่ระบุ' },
  { id: 'en-010', title: 'Photograph', artist: 'Ed Sheeran', language: 'international', genre: 'Pop', key: 'E', capo: 'ไม่ระบุ' },
  { id: 'en-011', title: 'Shape of You', artist: 'Ed Sheeran', language: 'international', genre: 'Pop', key: 'C#m', capo: 'ไม่ระบุ' },
  { id: 'en-012', title: 'Someone Like You', artist: 'Adele', language: 'international', genre: 'Pop', key: 'A', capo: 'ไม่ระบุ' },
  { id: 'en-013', title: 'Rolling in the Deep', artist: 'Adele', language: 'international', genre: 'Pop', key: 'Cm', capo: 'ไม่ระบุ' },
  { id: 'en-014', title: 'Easy on Me', artist: 'Adele', language: 'international', genre: 'Pop', key: 'F', capo: 'ไม่ระบุ' },
  { id: 'en-015', title: 'All of Me', artist: 'John Legend', language: 'international', genre: 'Pop', key: 'Ab', capo: 'ไม่ระบุ' },
  { id: 'en-016', title: 'Counting Stars', artist: 'OneRepublic', language: 'international', genre: 'Pop', key: 'Am', capo: 'ไม่ระบุ' },
  { id: 'en-017', title: 'Apologize', artist: 'OneRepublic', language: 'international', genre: 'Pop', key: 'Cm', capo: 'ไม่ระบุ' },
  { id: 'en-018', title: 'Viva la Vida', artist: 'Coldplay', language: 'international', genre: 'Pop', key: 'Ab', capo: 'ไม่ระบุ' },
  { id: 'en-019', title: 'Yellow', artist: 'Coldplay', language: 'international', genre: 'Rock', key: 'B', capo: 'ไม่ระบุ' },
  { id: 'en-020', title: 'The Scientist', artist: 'Coldplay', language: 'international', genre: 'Pop', key: 'F', capo: 'ไม่ระบุ' },
  { id: 'en-021', title: 'Fix You', artist: 'Coldplay', language: 'international', genre: 'Rock', key: 'Eb', capo: 'ไม่ระบุ' },
  { id: 'en-022', title: 'A Sky Full of Stars', artist: 'Coldplay', language: 'international', genre: 'Pop', key: 'F#', capo: 'ไม่ระบุ' },
  { id: 'en-023', title: 'Creep', artist: 'Radiohead', language: 'international', genre: 'Rock', key: 'G', capo: 'ไม่ระบุ' },
  { id: 'en-024', title: 'High and Dry', artist: 'Radiohead', language: 'international', genre: 'Rock', key: 'E', capo: 'ไม่ระบุ' },
  { id: 'en-025', title: 'I\'m Yours', artist: 'Jason Mraz', language: 'international', genre: 'Pop', key: 'B', capo: 'ไม่ระบุ' },
  { id: 'en-026', title: 'Lucky', artist: 'Jason Mraz ft. Colbie Caillat', language: 'international', genre: 'Pop', key: 'C', capo: 'ไม่ระบุ' },
  { id: 'en-027', title: 'Rude', artist: 'MAGIC!', language: 'international', genre: 'Pop', key: 'F#', capo: 'ไม่ระบุ' },
  { id: 'en-028', title: 'Stay With Me', artist: 'Sam Smith', language: 'international', genre: 'Pop', key: 'C', capo: 'ไม่ระบุ' },
  { id: 'en-029', title: 'Too Good at Goodbyes', artist: 'Sam Smith', language: 'international', genre: 'Pop', key: 'D', capo: 'ไม่ระบุ' },
  { id: 'en-030', title: 'Hallelujah', artist: 'Leonard Cohen', language: 'international', genre: 'Folk', key: 'C', capo: 'ไม่ระบุ' },
  { id: 'en-031', title: 'Imagine', artist: 'John Lennon', language: 'international', genre: 'Pop', key: 'C', capo: 'ไม่ระบุ' },
  { id: 'en-032', title: 'Stand by Me', artist: 'Ben E. King', language: 'international', genre: 'Pop', key: 'A', capo: 'ไม่ระบุ' },
  { id: 'en-033', title: 'Knockin\' on Heaven\'s Door', artist: 'Bob Dylan', language: 'international', genre: 'Folk', key: 'G', capo: 'ไม่ระบุ' },
  { id: 'en-034', title: 'Blowin\' in the Wind', artist: 'Bob Dylan', language: 'international', genre: 'Folk', key: 'D', capo: 'ไม่ระบุ' },
  { id: 'en-035', title: 'Let Her Go', artist: 'Passenger', language: 'international', genre: 'Folk', key: 'G', capo: 'ไม่ระบุ' },
  { id: 'en-036', title: 'Ho Hey', artist: 'The Lumineers', language: 'international', genre: 'Folk', key: 'C', capo: 'ไม่ระบุ' },
  { id: 'en-037', title: 'Budapest', artist: 'George Ezra', language: 'international', genre: 'Folk', key: 'F', capo: 'ไม่ระบุ' },
  { id: 'en-038', title: 'Take Me Home, Country Roads', artist: 'John Denver', language: 'international', genre: 'Folk', key: 'A', capo: 'ไม่ระบุ' },
  { id: 'en-039', title: 'Leaving on a Jet Plane', artist: 'John Denver', language: 'international', genre: 'Folk', key: 'G', capo: 'ไม่ระบุ' },
  { id: 'en-040', title: 'Sweet Home Alabama', artist: 'Lynyrd Skynyrd', language: 'international', genre: 'Rock', key: 'D', capo: 'ไม่ระบุ' },
  { id: 'en-041', title: 'Free Fallin\'', artist: 'Tom Petty', language: 'international', genre: 'Rock', key: 'F', capo: 'ไม่ระบุ' },
  { id: 'en-042', title: 'Iris', artist: 'Goo Goo Dolls', language: 'international', genre: 'Rock', key: 'Bm', capo: 'ไม่ระบุ' },
  { id: 'en-043', title: 'Boulevard of Broken Dreams', artist: 'Green Day', language: 'international', genre: 'Rock', key: 'Fm', capo: 'ไม่ระบุ' },
  { id: 'en-044', title: 'Wake Me Up When September Ends', artist: 'Green Day', language: 'international', genre: 'Rock', key: 'G', capo: 'ไม่ระบุ' },
  { id: 'en-045', title: '21 Guns', artist: 'Green Day', language: 'international', genre: 'Rock', key: 'Dm', capo: 'ไม่ระบุ' },
  { id: 'en-046', title: 'Smells Like Teen Spirit', artist: 'Nirvana', language: 'international', genre: 'Rock', key: 'F', capo: 'ไม่ระบุ' },
  { id: 'en-047', title: 'Come As You Are', artist: 'Nirvana', language: 'international', genre: 'Rock', key: 'Em', capo: 'ไม่ระบุ' },
  { id: 'en-048', title: 'Nothing Else Matters', artist: 'Metallica', language: 'international', genre: 'Rock', key: 'Em', capo: 'ไม่ระบุ' },
  { id: 'en-049', title: 'Enter Sandman', artist: 'Metallica', language: 'international', genre: 'Rock', key: 'Em', capo: 'ไม่ระบุ' },
  { id: 'en-050', title: 'Zombie', artist: 'The Cranberries', language: 'international', genre: 'Rock', key: 'Em', capo: 'ไม่ระบุ' },
  { id: 'en-051', title: 'Linger', artist: 'The Cranberries', language: 'international', genre: 'Rock', key: 'D', capo: 'ไม่ระบุ' },
  { id: 'en-052', title: 'With or Without You', artist: 'U2', language: 'international', genre: 'Rock', key: 'D', capo: 'ไม่ระบุ' },
  { id: 'en-053', title: 'One', artist: 'U2', language: 'international', genre: 'Rock', key: 'Am', capo: 'ไม่ระบุ' },
  { id: 'en-054', title: 'Every Breath You Take', artist: 'The Police', language: 'international', genre: 'Rock', key: 'A', capo: 'ไม่ระบุ' },
  { id: 'en-055', title: 'Shape of My Heart', artist: 'Sting', language: 'international', genre: 'Pop', key: 'F#m', capo: 'ไม่ระบุ' },
  { id: 'en-056', title: 'Tears in Heaven', artist: 'Eric Clapton', language: 'international', genre: 'Folk', key: 'A', capo: 'ไม่ระบุ' },
  { id: 'en-057', title: 'Wonderful Tonight', artist: 'Eric Clapton', language: 'international', genre: 'Folk', key: 'G', capo: 'ไม่ระบุ' },
  { id: 'en-058', title: 'Your Song', artist: 'Elton John', language: 'international', genre: 'Pop', key: 'Eb', capo: 'ไม่ระบุ' },
  { id: 'en-059', title: 'Rocket Man', artist: 'Elton John', language: 'international', genre: 'Pop', key: 'Bb', capo: 'ไม่ระบุ' },
  { id: 'en-060', title: 'Bohemian Rhapsody', artist: 'Queen', language: 'international', genre: 'Rock', key: 'Bb', capo: 'ไม่ระบุ' },
  { id: 'en-061', title: 'Love of My Life', artist: 'Queen', language: 'international', genre: 'Rock', key: 'C', capo: 'ไม่ระบุ' },
  { id: 'en-062', title: 'We Are the Champions', artist: 'Queen', language: 'international', genre: 'Rock', key: 'Cm', capo: 'ไม่ระบุ' },
  { id: 'en-063', title: 'Shallow', artist: 'Lady Gaga & Bradley Cooper', language: 'international', genre: 'Pop', key: 'G', capo: 'ไม่ระบุ' },
  { id: 'en-064', title: 'Bad Romance', artist: 'Lady Gaga', language: 'international', genre: 'Pop', key: 'Am', capo: 'ไม่ระบุ' },
  { id: 'en-065', title: 'Blank Space', artist: 'Taylor Swift', language: 'international', genre: 'Pop', key: 'F', capo: 'ไม่ระบุ' },
  { id: 'en-066', title: 'Love Story', artist: 'Taylor Swift', language: 'international', genre: 'Pop', key: 'D', capo: 'ไม่ระบุ' },
  { id: 'en-067', title: 'You Belong With Me', artist: 'Taylor Swift', language: 'international', genre: 'Pop', key: 'F#', capo: 'ไม่ระบุ' },
  { id: 'en-068', title: 'Anti-Hero', artist: 'Taylor Swift', language: 'international', genre: 'Pop', key: 'E', capo: 'ไม่ระบุ' },
  { id: 'en-069', title: 'Drivers License', artist: 'Olivia Rodrigo', language: 'international', genre: 'Pop', key: 'Bb', capo: 'ไม่ระบุ' },
  { id: 'en-070', title: 'Good 4 U', artist: 'Olivia Rodrigo', language: 'international', genre: 'Rock', key: 'F#', capo: 'ไม่ระบุ' }
];
