import {initializeApp} from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js';
import {auth,loginWithGoogle,logout} from '/firebase-auth.js';
import {GoogleAuthProvider,OAuthProvider,signInWithPopup,getAuth,setPersistence,inMemoryPersistence,signOut,onAuthStateChanged} from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js';
import {getFirestore,doc,onSnapshot,runTransaction} from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js';
import {dayKey,todayTasks,loadCalendar,scanMail,prioritizeMail,loadWeather,loadMicrosoftCalendar,scanMicrosoftMail,safeMailLink,TIME_ZONE} from './data.js';
const $=id=>document.getElementById(id), db=getFirestore(auth.app,'ai-studio-remixtaithaiapp-75e1f35e-2cc5-45a8-8a42-e4a81ea8cffb');
const connectorAuth=getAuth(initializeApp(auth.app.options,'personal-news-connectors'));const connectorReady=setPersistence(connectorAuth,inMemoryPersistence);
let currentUser=null,epoch=0,stop=()=>{},state={tasks:[],routines:[],area:''},events=[],calendarReady=false,refreshing=false,activeDay=dayKey(),connections=new Map(),connecting=false;
function say(id,text){$(id).textContent=text;}
function node(tag,text){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;}
function clock(d){return new Intl.DateTimeFormat('th-TH',{timeZone:TIME_ZONE,hour:'2-digit',minute:'2-digit'}).format(new Date(d));}
function dateHeader(){say('date',new Intl.DateTimeFormat('th-TH',{timeZone:TIME_ZONE,dateStyle:'full'}).format(new Date()));}
function clearPrivate(){connections.clear();$('accounts').replaceChildren();signOut(connectorAuth).catch(()=>{});events=[];calendarReady=false;state={tasks:[],routines:[],area:''};['events','mail','tasks','routines','weather'].forEach(id=>$(id).replaceChildren());say('calendar-status','ยังไม่เชื่อม Google Calendar');say('mail-status','ยังไม่เชื่อม Gmail');say('updated','ยังไม่ได้ดึงข้อมูล');say('sync-status','');say('reader','สำหรับเจ้าของบัญชี');say('auth-error','');$('settings').close();}
function summarize(){const tasks=todayTasks(state.tasks).filter(x=>!x.done);say('headline',calendarReady?`วันนี้มี ${events.length} นัดหมาย และ ${tasks.length} งานที่ยังไม่เสร็จ`:'เปิดดูแผนจริงของวันนี้');say('summary',calendarReady?'นัดหมายจากบัญชีที่อ่านสำเร็จ • งานที่บันทึกเอง • ตรวจสถานะรายบัญชีด้านบน':'ยังตรวจตารางทั้งหมดไม่ได้ เชื่อมปฏิทินเพื่อดูนัดหมาย • งานที่บันทึกแสดงได้ทันที');}
async function save(change){if(!currentUser)throw new Error('กรุณาเข้าสู่ระบบ');const uid=currentUser.uid;await runTransaction(db,async tx=>{const ref=doc(db,'users',uid);const snap=await tx.get(ref);const old=snap.data()?.dailyPaper||{tasks:[],routines:[],area:''};const next=change({...old,tasks:Array.isArray(old.tasks)?old.tasks:[],routines:Array.isArray(old.routines)?old.routines:[]});tx.set(ref,{dailyPaper:next},{merge:true});});}
function renderState(){renderAccounts();const tasks=todayTasks(state.tasks);$('tasks').replaceChildren();for(const task of tasks){const li=node('li'),line=node('div');line.className='taskline';const label=node('label'),check=node('input');check.type='checkbox';check.checked=task.done===true;const text=node('span',`${task.time?task.time+' · ':''}${task.title}`);label.append(check,text);line.append(label);li.append(line);check.addEventListener('change',async()=>{const done=check.checked;check.disabled=true;try{await save(s=>({...s,tasks:s.tasks.map(t=>t.id===task.id?{...t,done}:t)}));}catch(e){check.checked=!done;say('task-status','บันทึกไม่สำเร็จ: '+e.message);}finally{check.disabled=false;}});$('tasks').append(li);}say('task-status',tasks.length?`ทำแล้ว ${tasks.filter(t=>t.done).length} จาก ${tasks.length} งาน`:'ยังไม่มีงานที่คุณบันทึกสำหรับวันนี้');$('routines').replaceChildren();for(const r of state.routines){const li=node('li');li.append(node('time',r.time),node('b',r.title));$('routines').append(li);}say('routine-status',state.routines.length?'รูทีนที่คุณเลือกใช้':'ยังไม่มีรูทีนที่เลือกใช้ กด “จัดรูทีนและพื้นที่” เพื่อปรับแผนที่เสนอ');say('area-title','รังสิตและดอนเมือง');summarize();}
function renderEvents(){ $('events').replaceChildren();for(const e of events){const li=node('li'),when=e.start?.dateTime?clock(e.start.dateTime):'ทั้งวัน',content=node('div'),link=node('a',e.summary||'ไม่ระบุชื่อนัดหมาย');link.href=safeMailLink(e.htmlLink,'https://calendar.google.com/');link.target='_blank';link.rel='noopener noreferrer';const title=node('h4');title.append(link);content.append(title,node('small',e.account||''));if(e.location)content.append(node('p',e.location));if(e.start?.dateTime&&e.end?.dateTime)content.append(node('p',`${clock(e.start.dateTime)}–${clock(e.end.dateTime)} น.`));li.append(node('time',when),content);$('events').append(li);}say('calendar-status',events.length?'ปฏิทินหลักของบัญชีที่อ่านสำเร็จ • เวลาไทย':'ไม่พบนัดหมายในบัญชีที่อ่านสำเร็จวันนี้');summarize();}
function renderMail(all){const ranked=all.map(m=>prioritizeMail(m)).sort((a,b)=>b.score-a.score||Number(b.internalDate)-Number(a.internalDate));const items=ranked.filter(m=>m.reasons.length&&m.age<=30).slice(0,20);$('mail').replaceChildren();for(const m of items){const headers=m.payload?.headers||[],header=name=>headers.find(h=>h.name.toLowerCase()===name.toLowerCase())?.value||'';const box=node('article');box.className='mail';const a=node('a',header('Subject')||'(ไม่มีหัวเรื่อง)');a.href=safeMailLink(m.webLink,`https://mail.google.com/mail/u/${encodeURIComponent(m.account||currentUser.email)}/#all/${encodeURIComponent(m.threadId||m.id)}`);a.target='_blank';a.rel='noopener noreferrer';box.append(a,node('p',m.reasons.join(' · ')),node('p',header('From')),node('small',m.account||''),node('small',new Intl.DateTimeFormat('th-TH',{timeZone:TIME_ZONE,dateStyle:'medium',timeStyle:'short'}).format(new Date(Number(m.internalDate)))));$('mail').append(box);}say('mail-status',`ตรวจแล้ว ${all.length} ฉบับ • คัดเรื่องใน 30 วันล่าสุดได้ ${items.length} ฉบับ${items.length?'':' • ยังไม่พบหัวข้อที่ตรงเกณฑ์'}`);}
function renderAccounts(){ $('accounts').replaceChildren();for(const a of state.accounts||[]){const row=node('div');row.className='controls';const info=node('span',`${a.email} · ${connections.get(a.email)?.status||'ยังไม่เชื่อมในครั้งนี้'}`),button=node('button',connections.has(a.email)?'เชื่อมใหม่':'อนุญาตอ่านข้อมูล');button.disabled=connecting;button.onclick=()=>connect(a,button);row.append(info,button);$('accounts').append(row);}}
async function refresh(){if(!currentUser||refreshing)return;refreshing=true;const turn=epoch,uid=currentUser.uid,unchanged=()=>turn===epoch&&currentUser?.uid===uid;let results=[],success=0;try{for(const [email,c] of connections){if(!unchanged())return;c.status='กำลังอ่านข้อมูล';renderAccounts();const options={isActive:unchanged,onProgress:n=>{if(unchanged()){c.status=`กำลังตรวจเมล ${n} ฉบับ`;renderAccounts();}}};let errors=[];try{const data=await(c.provider==='microsoft'?loadMicrosoftCalendar(c.token,options):loadCalendar(c.token));if(!unchanged())return;results.push(...data.map(e=>({...e,account:email})));success++;}catch(e){errors.push('ปฏิทิน: '+e.message);}try{const data=await(c.provider==='microsoft'?scanMicrosoftMail(c.token,{...options,incremental:c.scanned}):scanMail(c.token,{...options,query:c.scanned?'newer_than:2d':''}));if(!unchanged())return;data.forEach(m=>c.mail.set(m.id,{...m,account:email}));c.scanned=true;c.mailOk=true;}catch(e){c.mailOk=false;errors.push('อีเมล: '+e.message);}if(!unchanged())return;c.status=errors.length?errors.join(' / '):'อัปเดตแล้ว '+clock(new Date())+' น.';renderAccounts();}if(!unchanged())return;events=results.sort((a,b)=>(a.start?.dateTime||a.start?.date||'').localeCompare(b.start?.dateTime||b.start?.date||''));calendarReady=success>0;renderEvents();if(!success)say('calendar-status','ยังไม่มีบัญชีที่อ่านปฏิทินได้สำเร็จ');const all=[...connections.values()].filter(c=>c.mailOk).flatMap(c=>[...c.mail.values()]);renderMail(all);if(![...connections.values()].some(c=>c.mailOk))say('mail-status','ยังไม่มีบัญชีที่อ่านอีเมลได้สำเร็จ');say('updated','ตรวจการเชื่อมต่อล่าสุด '+clock(new Date())+' น.');say('sync-status',`อ่านปฏิทินสำเร็จ ${success}/${(state.accounts||[]).length} บัญชี · อ่านเมลสำเร็จ ${[...connections.values()].filter(c=>c.mailOk).length}/${(state.accounts||[]).length} บัญชี`);}finally{refreshing=false;}}
async function connect(account,button){if(!currentUser||connecting)return;connecting=true;button.disabled=true;const start=epoch;try{await connectorReady;const provider=account.provider==='microsoft'?new OAuthProvider('microsoft.com'):new GoogleAuthProvider();if(account.provider==='microsoft'){provider.addScope('Mail.Read');provider.addScope('Calendars.Read');provider.addScope('User.Read');}else{provider.addScope('https://www.googleapis.com/auth/calendar.events.readonly');provider.addScope('https://www.googleapis.com/auth/gmail.readonly');}provider.setCustomParameters({login_hint:account.email,prompt:'select_account'});const result=await signInWithPopup(connectorAuth,provider);if(start!==epoch)return;const actual=(result.user.email||'').toLowerCase();if(actual!==account.email.toLowerCase())throw new Error('ACCOUNT_MISMATCH');const credential=account.provider==='microsoft'?OAuthProvider.credentialFromResult(result):GoogleAuthProvider.credentialFromResult(result);if(!credential?.accessToken)throw new Error('NO_TOKEN');connections.set(account.email,{provider:account.provider,token:credential.accessToken,mail:new Map(),scanned:false,status:'เชื่อมแล้ว'});say('auth-error','');await refresh();}catch(e){say('auth-error',e.message==='ACCOUNT_MISMATCH'?'บัญชีที่เลือกไม่ตรงกับอีเมลที่เพิ่มไว้ โปรดเลือกใหม่':e.code==='auth/operation-not-allowed'?'ผู้ดูแลแอปต้องเปิดผู้ให้บริการ Microsoft ใน Firebase และตั้งค่า Entra ก่อน':e.code==='auth/popup-closed-by-user'?'ยกเลิกการเชื่อมต่อแล้ว':`เชื่อมบัญชีไม่ได้ (${e.code||e.message}) ต้องตรวจการอนุญาตและการเปิด API ของบัญชีนี้`);}finally{await signOut(connectorAuth).catch(()=>{});connecting=false;renderAccounts();}}
$('login').onclick=()=>loginWithGoogle().catch(e=>say('auth-error',`เข้าสู่ระบบไม่ได้ (${e.code||'connection-error'})`));$('logout').onclick=()=>logout().catch(()=>say('auth-error','ออกจากระบบไม่สำเร็จ'));$('refresh').onclick=refresh;
$('account-form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,data=new FormData(f),email=String(data.get('email')).trim().toLowerCase(),provider=String(data.get('provider'));try{await save(s=>{const accounts=s.accounts||[];if(accounts.some(a=>a.email===email))return s;if(accounts.length>=8)throw new Error('เพิ่มได้สูงสุด 8 บัญชี');return {...s,accounts:[...accounts,{email,provider}]};});f.reset();}catch(err){say('auth-error','เพิ่มบัญชีไม่ได้: '+err.message);}};
$('settings-open').onclick=()=>{const f=$('settings-form');f.elements.area.value=state.area||'';['morning','focus','night'].forEach((key,i)=>{if(state.routines[i])f.elements[key].value=state.routines[i].time;});$('settings').showModal();};$('settings-close').onclick=()=>$('settings').close();
$('task-form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,b=f.querySelector('button'),data=new FormData(f),title=String(data.get('title')).trim();if(!title)return;const task={id:crypto.randomUUID(),title:title.slice(0,160),date:String(data.get('date')),time:String(data.get('time')||''),done:false};b.disabled=true;try{await save(s=>{if(s.tasks.length>=500)throw new Error('งานครบ 500 รายการ กรุณาจัดการข้อมูลก่อนเพิ่ม');return {...s,tasks:[...s.tasks,task]};});f.elements.title.value='';say('sync-status','บันทึกงานลงบัญชีแล้ว');}catch(err){say('task-status','บันทึกไม่สำเร็จ: '+err.message);}finally{b.disabled=false;}};
$('settings-form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,b=f.querySelector('button'),data=new FormData(f);b.disabled=true;try{await save(s=>({...s,area:String(data.get('area')).trim().slice(0,120),routines:[{time:String(data.get('morning')),title:'กินมื้อเช้าและตรวจนัดวันนี้'},{time:String(data.get('focus')),title:'โฟกัสงานทีละเรื่อง สลับพัก'},{time:String(data.get('night')),title:'เตรียมของและเช็กนัดวันพรุ่งนี้'}]}));$('settings').close();}catch(err){say('auth-error','บันทึกรูทีนไม่ได้: '+err.message);}finally{b.disabled=false;}};
onAuthStateChanged(auth,user=>{if(user?.uid===currentUser?.uid)return;epoch++;stop();clearPrivate();currentUser=user;$('private').hidden=!user;$('signed-out').hidden=!!user;if(!user)return;say('reader',user.displayName||user.email);$('account-form').elements.email.value=user.email||'';state={tasks:[],routines:[],area:'รังสิตและดอนเมือง'};renderState();refreshWeather();const snapshotEpoch=epoch;stop=onSnapshot(doc(db,'users',user.uid),snapshot=>{if(snapshotEpoch!==epoch||currentUser?.uid!==user.uid)return;state={tasks:[],routines:[],area:'',...snapshot.data()?.dailyPaper};if(!Array.isArray(state.tasks))state.tasks=[];if(!Array.isArray(state.routines))state.routines=[];renderState();},()=>say('task-status','อ่านข้อมูลที่บันทึกไม่ได้ กรุณาลองเข้าสู่ระบบใหม่'));});
async function refreshWeather(){const turn=epoch;try{const items=await loadWeather();if(turn!==epoch||!currentUser)return;$('weather').replaceChildren();for(const item of items){const d=item.daily,box=node('article');box.append(node('h4',item.name),node('p',`${d.temperature_2m_min[0]??'—'}–${d.temperature_2m_max[0]??'—'} °C · โอกาสฝนสูงสุด ${d.precipitation_probability_max[0]??'—'}%`),node('p',`ปริมาณฝนรวมที่คาดการณ์ ${d.precipitation_sum[0]??'—'} มม.`));$('weather').append(box);}say('area-status','พยากรณ์วันนี้ • ดึงล่าสุด '+clock(new Date())+' น. • Open-Meteo');}catch{if(turn===epoch)say('area-status','ดึงพยากรณ์อากาศไม่ได้ ยังตรวจสภาพอากาศไม่ได้');}}
dateHeader();$('task-form').elements.date.value=activeDay;
setInterval(()=>{if(document.hidden||!currentUser)return;const day=dayKey();if(day!==activeDay){activeDay=day;async function refreshWeather(){const turn=epoch;try{const items=await loadWeather();if(turn!==epoch||!currentUser)return;$('weather').replaceChildren();for(const item of items){const d=item.daily,box=node('article');box.append(node('h4',item.name),node('p',`${d.temperature_2m_min[0]??'—'}–${d.temperature_2m_max[0]??'—'} °C · โอกาสฝนสูงสุด ${d.precipitation_probability_max[0]??'—'}%`),node('p',`ปริมาณฝนรวมที่คาดการณ์ ${d.precipitation_sum[0]??'—'} มม.`));$('weather').append(box);}say('area-status','พยากรณ์วันนี้ • ดึงล่าสุด '+clock(new Date())+' น. • Open-Meteo');}catch{if(turn===epoch)say('area-status','ดึงพยากรณ์อากาศไม่ได้ ยังตรวจสภาพอากาศไม่ได้');}}
dateHeader();$('task-form').elements.date.value=day;events=[];calendarReady=false;renderState();}refresh();refreshWeather();},300000);
