import {renderMarkets} from './markets.js';
import {importPair,decrypt,encrypt,validateArchive,safeLink,bangkokDate} from './crypto.js';
const $=id=>document.getElementById(id);let pairing,archive,selected,db,notes={tasks:[],routine:null},busy=false;
const text=(id,value)=>{$(id).textContent=value||'';};
const status=(value,error=false)=>{text('status',value);$('status').classList.toggle('error',error);};
const dateLabel=d=>new Date(d+'T12:00:00+07:00').toLocaleDateString('th-TH',{dateStyle:'full',timeZone:'Asia/Bangkok'});
const timeLabel=d=>new Date(d).toLocaleString('th-TH',{dateStyle:'short',timeStyle:'short',timeZone:'Asia/Bangkok'});
function el(tag,value,cls){const n=document.createElement(tag);n.textContent=value||'';if(cls)n.className=cls;return n;}
async function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open('taithai-new',1);r.onupgradeneeded=()=>r.result.createObjectStore('private');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function dbOp(method,id,value){return new Promise((resolve,reject)=>{const tx=db.transaction('private',method==='get'?'readonly':'readwrite');const s=tx.objectStore('private');const r=method==='get'?s.get(id):method==='put'?s.put(value,id):s.delete(id);tx.oncomplete=()=>resolve(r.result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}
async function getPublished(p){const r=await fetch(`/taithai/news/feeds/${p.feed}.json?t=${Date.now()}`,{cache:'no-store',credentials:'omit',referrerPolicy:'no-referrer'});if(!r.ok)throw new Error('ไม่พบฉบับข่าวของรหัสนี้');const box=await r.json();const a=validateArchive(await decrypt(p.key,box));return {box,a};}
async function saveNotes(){await dbOp('put','notes',await encrypt(pairing.key,notes,'taithai-new-notes-v1'));}
function article(item){const n=el('article','','mail');n.append(el('h4',item.title),el('p',item.body));if(item.source){const a=el('a',item.source.label||'อ่านต้นฉบับ','source');const href=safeLink(item.source.url);if(href){a.href=href;a.target='_blank';a.rel='noopener noreferrer';n.append(a);}}return n;}
function drawNotes(){const list=$('tasks');list.replaceChildren();const tasks=notes.tasks.filter(t=>t.date===selected.date);if(!tasks.length)list.append(el('p','ยังไม่มีงานส่วนตัวที่บันทึกไว้สำหรับวันนี้ เช่น ซักผ้าหรือซื้อของ จึงยังไม่สรุปว่าต้องทำอะไร','status'));for(const t of tasks){const li=el('li');const label=el('label');const input=document.createElement('input');input.type='checkbox';input.checked=t.done;input.onchange=async()=>{t.done=input.checked;try{await saveNotes();}catch{status('บันทึกงานไม่สำเร็จ กรุณาลองใหม่',true);}};label.append(input,el('span',t.title));li.append(label);list.append(li);}const routine=$('routines');routine.replaceChildren();if(!notes.routine){routine.append(el('li','ยังไม่ได้เลือกรูทีน เปิด “รูทีนของฉัน” เพื่อดูแผนที่ออกแบบให้และปรับเวลา'));return;}for(const [key,body] of [['morning','เริ่มวัน · เช็กข่าวและกินมื้อเช้า'],['focus','ทำงานค้าง · เลือกหนึ่งเรื่องสำคัญ'],['night','ปิดวัน · เช็กของใช้และเตรียมพรุ่งนี้']]){const li=el('li');li.append(el('time',notes.routine[key]),el('span',body));routine.append(li);}}
function render(id){selected=archive.editions.find(e=>e.id===id)||archive.editions[0];$('pairing').hidden=true;$('private').hidden=false;text('date',dateLabel(selected.date));text('updated','จัดทำ '+timeLabel(selected.createdAt));text('eyebrow',selected.date===bangkokDate()?'ประเด็นสำคัญประจำวัน':'ฉบับย้อนหลัง · ข้อมูล ณ เวลาจัดทำ');for(const key of ['headline','summary','room','coverage','gaps'])text(key,selected[key]);text('schedule-note',selected.scheduleNote);text('worker','ยังไม่ได้เชื่อมคอมที่จัดทำข่าว · ปุ่มอัปเดตจะตรวจฉบับที่เผยแพร่ล่าสุดให้ ขณะนี้ยังสั่งอ่านเมลและ Teams รอบใหม่จากเว็บไม่ได้');const events=$('events');events.replaceChildren();for(const e of selected.events){const li=el('li');li.append(el('time',e.time));const detail=el('div');detail.append(article(e));li.append(detail);events.append(li);}for(const key of ['stories','deadlines','alerts'])$(key).replaceChildren(...selected[key].map(article));const select=$('editions');select.replaceChildren();for(const e of archive.editions){const option=el('option',dateLabel(e.date)+' · '+timeLabel(e.createdAt));option.value=e.id;select.append(option);}select.value=selected.id;$('task-form').elements.date.value=bangkokDate();drawNotes();drawMarkets();}
function drawMarkets(){if(selected)renderMarkets($('markets'),selected.markets,{historical:selected.id!==archive.editions[0].id});}
setInterval(drawMarkets,60000);
document.addEventListener('visibilitychange',()=>{if(!document.hidden)drawMarkets();});
async function refresh(){if(busy||!pairing)return;busy=true;$('refresh').disabled=true;status('กำลังตรวจฉบับล่าสุด…');try{const previous=archive?.editions[0]?.id;const {box,a}=await getPublished(pairing);await dbOp('put','archive',box);archive=a;render(a.editions[0].id);status(previous===a.editions[0].id?'ตรวจแล้ว ฉบับนี้ยังเป็นฉบับล่าสุด · ยังไม่ได้อ่านเมล Teams หรือราคาหุ้นรอบใหม่':'โหลดฉบับข่าวล่าสุดแล้ว');}catch{status('อัปเดตไม่สำเร็จ กำลังแสดงฉบับที่บันทึกไว้ กรุณาตรวจการเชื่อมต่อ',true);}finally{busy=false;$('refresh').disabled=false;}}
$('pair-form').onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;const button=e.currentTarget.querySelector('button');button.disabled=true;status('กำลังจับคู่อุปกรณ์…');try{const raw=$('pair-file').files[0]?await $('pair-file').files[0].text():$('pair-code').value;const candidate=await importPair(JSON.parse(raw));const {box,a}=await getPublished(candidate);await dbOp('put','pairing',candidate);await dbOp('put','archive',box);pairing=candidate;archive=a;notes={tasks:[],routine:null};await saveNotes();$('pair-code').value='';$('pair-file').value='';render();status('จับคู่แล้ว ครั้งถัดไปเปิดอ่านได้ทันทีบนเบราว์เซอร์นี้');}catch{status('จับคู่ไม่สำเร็จ ตรวจไฟล์หรือรหัสจับคู่และการเชื่อมต่อ แล้วลองอีกครั้ง',true);}finally{busy=false;button.disabled=false;}};
$('refresh').onclick=refresh;$('history').onclick=()=>{$('editions').hidden=!$('editions').hidden;if(!$('editions').hidden){$('editions').focus();status(archive.editions.length===1?'ขณะนี้มี 1 ฉบับจริง เมื่อจัดทำฉบับใหม่ ฉบับเก่าจะอยู่ที่นี่':'เลือกฉบับที่ต้องการย้อนอ่าน');}};$('editions').onchange=e=>{render(e.target.value);status('กำลังอ่านข่าว ณ เวลาจัดทำฉบับที่เลือก');};
$('forget').onclick=async()=>{if(!confirm('ยกเลิกการจับคู่และลบงานที่บันทึกบนเครื่องนี้? คุณใช้ไฟล์จับคู่เปิดอ่านใหม่ได้'))return;try{for(const id of ['pairing','archive','notes'])await dbOp('delete',id);location.reload();}catch{status('ลบการจับคู่ไม่สำเร็จ กรุณาลองใหม่',true);}};
$('settings-open').onclick=()=>{if(notes.routine)for(const [k,v]of Object.entries(notes.routine))$('settings-form').elements[k].value=v;$('settings').showModal();};$('settings-close').onclick=()=>$('settings').close();
$('settings-form').onsubmit=async e=>{e.preventDefault();notes.routine=Object.fromEntries(new FormData(e.currentTarget));try{await saveNotes();drawNotes();$('settings').close();status('บันทึกรูทีนแล้ว');}catch{status('บันทึกรูทีนไม่สำเร็จ',true);}};
$('task-form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;const title=f.elements.title.value.trim();if(!title)return;const task={id:crypto.randomUUID(),title,date:f.elements.date.value,done:false};notes.tasks.push(task);try{await saveNotes();f.elements.title.value='';drawNotes();status(task.date===selected.date?'บันทึกงานแล้ว':'บันทึกงานตามวันที่เลือกแล้ว งานจะแสดงเมื่ออ่านฉบับวันนั้น');}catch{notes.tasks.pop();status('บันทึกงานไม่สำเร็จ',true);}};
try{db=await openDB();pairing=await dbOp('get','pairing');if(pairing){const saved=await dbOp('get','archive');if(saved){archive=validateArchive(await decrypt(pairing.key,saved));const savedNotes=await dbOp('get','notes');if(savedNotes)notes=await decrypt(pairing.key,savedNotes,'taithai-new-notes-v1');render();}await refresh();}}catch{status('ไม่สามารถเปิดข้อมูลที่บันทึกไว้ได้ กรุณาจับคู่ใหม่ และอนุญาตให้เบราว์เซอร์เก็บข้อมูลของเว็บไซต์นี้',true);$('pairing').hidden=false;}
